### ISSUE TITLE
Maintaining the ability to jump-click to original source file?

### ISSUE THREAD

**Issue by natew** [run-z/rollup-plugin-flat-dts#1]
Love love love the plugin, just moved over to it and it improved CI builds from ~2m to 11s because we can parallelize it fully now!

One downgrade from before was that having the separate .d.ts files meant in vscode ctrl+click would jump to the original file definition rather than the type file, which is really nice, but now it will jump to the bundled .d.ts file instead of the original.

Any idea if this is possible to make work with this strategy?

**Comment by surol** [comment]
Thanks. Glad it helps.

Yeah, the lack of point-clicking annoys me a lot too. That's what I _really_ want to fix.

I am almost certain this can be fixed by adding source maps to generated `.d.ts` files.

Thing is, I don't know how to handle source maps within TypeScript compiler internals. If someone point me out onto documentation or just a simple example of how to handle them, it would help.

**Comment by natew** [comment]
After a few days use:  Using this plugin actually sped up types in general so much on our stack it's huge. Autocomplete imports used to take a few seconds due to large types in a few areas, now are instant, huge win.

But yea, not jumping to source is a pretty big pain. I'd love to help here. Think there's some temporary hacky way we can just quickly take the existing .map and concat them all together? I know there's `source-map` which handles some things. I haven't looked at the internals. I'd sponsor some work here at some small amount if that helps though, as it'd help quite a bit.

**Comment by surol** [comment]
This feature is very important. So I'll have to figure out how to implement it. Just need to find some time.

**Comment by surol** [comment]
Fixed by #5.
Fixed version: 1.1.0

**Comment by natew** [comment]
it works :) thank you
